set_property PACKAGE_PIN A6 [get_ports {a}]
set_property PACKAGE_PIN E6 [get_ports {b}]
set_property PACKAGE_PIN A5 [get_ports {cout}]
set_property PACKAGE_PIN D8 [get_ports {cin}]
set_property BEL IOB33.OUTBUF [get_cells {cout_OBUF_inst}]
set_property LOC A5 [get_cells {cout_OBUF_inst}]
set_property BEL IOB33.OUTBUF [get_cells {s_OBUF_inst}]
set_property LOC C7 [get_cells {s_OBUF_inst}]
set_property BEL IOB33.INBUF_EN [get_cells {b_IBUF_inst}]
set_property LOC E6 [get_cells {b_IBUF_inst}]
set_property PACKAGE_PIN C7 [get_ports {s}]
set_property BEL IOB33.INBUF_EN [get_cells {cin_IBUF_inst}]
set_property LOC D8 [get_cells {cin_IBUF_inst}]
set_property BEL IOB33.INBUF_EN [get_cells {a_IBUF_inst}]
set_property LOC A6 [get_cells {a_IBUF_inst}]
set_property BEL SLICEM.C5LUT [get_cells {s_OBUF_inst_i_1}]
set_property LOC SLICE_X88Y141 [get_cells {s_OBUF_inst_i_1}]
set_property LOCK_PINS { I0:A1 I1:A2 I2:A3 } [get_cells {s_OBUF_inst_i_1}]
set_property BEL SLICEM.C6LUT [get_cells {cout_OBUF_inst_i_1}]
set_property LOC SLICE_X88Y141 [get_cells {cout_OBUF_inst_i_1}]
set_property LOCK_PINS { I0:A1 I1:A2 I2:A3 } [get_cells {cout_OBUF_inst_i_1}]
#set_property LOCK_PINS { I0:A1 I1:A2 I2:A3 } [get_cells -filter {NAME == cout_OBUF_inst_i_1 || NAME == s_OBUF_inst_i_1}]

#set_property LOCK_PINS { I0:A1 I1:A2 I2:A3 } [get_cells {s_OBUF_inst_i_1}]
#set_property BEL SLICEM.C6LUT [get_cells {cout_OBUF_inst_i_1}]
#set_property LOC SLICE_X88Y141 [get_cells {cout_OBUF_inst_i_1}]
#set_property LOCK_PINS { I0:A1 I1:A2 I2:A3 } [get_cells {cout_OBUF_inst_i_1}]
