set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[2]_inst}]
set_property LOC T9 [get_cells {fir_out_OBUF[2]_inst}]
set_property PACKAGE_PIN V17 [get_ports {fir_out[13]}]
set_property PACKAGE_PIN V12 [get_ports {fir_out[9]}]
set_property BEL IOB33.INBUF_EN [get_cells {sw_IBUF[7]_inst}]
set_property LOC L14 [get_cells {sw_IBUF[7]_inst}]
set_property PACKAGE_PIN U16 [get_ports {fir_out[14]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[15]_inst}]
set_property LOC U18 [get_cells {fir_out_OBUF[15]_inst}]
set_property BEL RAMB18E1.RAMB18E1 [get_cells {cg/font/addr_reg_reg}]
set_property LOC RAMB18_X0Y38 [get_cells {cg/font/addr_reg_reg}]
set_property BEL IOB33.INBUF_EN [get_cells {sw_IBUF[1]_inst}]
set_property LOC R12 [get_cells {sw_IBUF[1]_inst}]
set_property PACKAGE_PIN K18 [get_ports {btn[0]}]
set_property BEL IOB33.OUTBUF [get_cells {vgaRed_OBUF[2]_inst}]
set_property LOC T18 [get_cells {vgaRed_OBUF[2]_inst}]
set_property BEL IOB33.INBUF_EN [get_cells {clk_IBUF_inst}]
set_property LOC N15 [get_cells {clk_IBUF_inst}]
set_property BEL IOB33.OUTBUF [get_cells {vgaGreen_OBUF[3]_inst}]
set_property LOC N17 [get_cells {vgaGreen_OBUF[3]_inst}]
set_property BEL BUFG.BUFG [get_cells {clk_IBUF_BUFG_inst}]
set_property LOC BUFGCTRL_X0Y0 [get_cells {clk_IBUF_BUFG_inst}]
set_property PACKAGE_PIN U12 [get_ports {fir_out[10]}]
set_property PACKAGE_PIN T14 [get_ports {fir_out[22]}]
set_property PACKAGE_PIN R15 [get_ports {fir_out[23]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[14]_inst}]
set_property LOC U16 [get_cells {fir_out_OBUF[14]_inst}]
set_property PACKAGE_PIN N16 [get_ports {vgaBlue[3]}]
set_property BEL IOB33.OUTBUF [get_cells {vgaRed_OBUF[1]_inst}]
set_property LOC N14 [get_cells {vgaRed_OBUF[1]_inst}]
set_property BEL IOB33.INBUF_EN [get_cells {sw_IBUF[2]_inst}]
set_property LOC M18 [get_cells {sw_IBUF[2]_inst}]
set_property PACKAGE_PIN R13 [get_ports {sw[0]}]
set_property PACKAGE_PIN U11 [get_ports {fir_out[11]}]
set_property PACKAGE_PIN T11 [get_ports {fir_out[12]}]
set_property BEL IOB33.OUTBUF [get_cells {vgaGreen_OBUF[2]_inst}]
set_property LOC P18 [get_cells {vgaGreen_OBUF[2]_inst}]
set_property BEL IOB33.INBUF_EN [get_cells {sw_IBUF[3]_inst}]
set_property LOC L18 [get_cells {sw_IBUF[3]_inst}]
set_property PACKAGE_PIN P17 [get_ports {vgaBlue[2]}]
set_property BEL IOB33.OUTBUF [get_cells {vgaBlue_OBUF[0]_inst}]
set_property LOC P15 [get_cells {vgaBlue_OBUF[0]_inst}]
set_property PACKAGE_PIN V16 [get_ports {fir_out[17]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[6]_inst}]
set_property LOC U14 [get_cells {fir_out_OBUF[6]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[9]_inst}]
set_property LOC V12 [get_cells {fir_out_OBUF[9]_inst}]
set_property PACKAGE_PIN R17 [get_ports {vgaBlue[1]}]
set_property BEL IOB33.OUTBUF [get_cells {vgaRed_OBUF[3]_inst}]
set_property LOC R18 [get_cells {vgaRed_OBUF[3]_inst}]
set_property PACKAGE_PIN V15 [get_ports {fir_out[18]}]
set_property PACKAGE_PIN P15 [get_ports {vgaBlue[0]}]
set_property PACKAGE_PIN N17 [get_ports {vgaGreen[3]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[10]_inst}]
set_property LOC U12 [get_cells {fir_out_OBUF[10]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[7]_inst}]
set_property LOC V11 [get_cells {fir_out_OBUF[7]_inst}]
set_property PACKAGE_PIN M13 [get_ports {Hsync}]
set_property PACKAGE_PIN U18 [get_ports {fir_out[15]}]
set_property BEL IOB33.INBUF_EN [get_cells {sw_IBUF[5]_inst}]
set_property LOC L15 [get_cells {sw_IBUF[5]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[8]_inst}]
set_property LOC V10 [get_cells {fir_out_OBUF[8]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[11]_inst}]
set_property LOC U11 [get_cells {fir_out_OBUF[11]_inst}]
set_property PACKAGE_PIN P18 [get_ports {vgaGreen[2]}]
set_property PACKAGE_PIN R10 [get_ports {fir_out[0]}]
set_property BEL DSP48E1.DSP48E1 [get_cells {accum_reg}]
set_property LOC DSP48_X0Y22 [get_cells {accum_reg}]
set_property BEL IOB33.INBUF_EN [get_cells {sw_IBUF[6]_inst}]
set_property LOC M14 [get_cells {sw_IBUF[6]_inst}]
set_property PACKAGE_PIN U17 [get_ports {fir_out[16]}]
set_property PACKAGE_PIN L13 [get_ports {Vsync}]
set_property PACKAGE_PIN M16 [get_ports {vgaGreen[1]}]
set_property PACKAGE_PIN T10 [get_ports {fir_out[1]}]
set_property PACKAGE_PIN M14 [get_ports {sw[6]}]
set_property PACKAGE_PIN N15 [get_ports {clk}]
set_property BEL IOB33.OUTBUF [get_cells {vgaGreen_OBUF[0]_inst}]
set_property LOC M17 [get_cells {vgaGreen_OBUF[0]_inst}]
set_property BEL IOB33.INBUF_EN [get_cells {sw_IBUF[4]_inst}]
set_property LOC L16 [get_cells {sw_IBUF[4]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[18]_inst}]
set_property LOC V15 [get_cells {fir_out_OBUF[18]_inst}]
set_property PACKAGE_PIN M17 [get_ports {vgaGreen[0]}]
set_property PACKAGE_PIN L14 [get_ports {sw[7]}]
set_property PACKAGE_PIN T9 [get_ports {fir_out[2]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[12]_inst}]
set_property LOC T11 [get_cells {fir_out_OBUF[12]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[20]_inst}]
set_property LOC R16 [get_cells {fir_out_OBUF[20]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {vgaBlue_OBUF[1]_inst}]
set_property LOC R17 [get_cells {vgaBlue_OBUF[1]_inst}]
set_property PACKAGE_PIN T16 [get_ports {fir_out[19]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[4]_inst}]
set_property LOC T13 [get_cells {fir_out_OBUF[4]_inst}]
set_property PACKAGE_PIN U13 [get_ports {fir_out[3]}]
set_property BEL IOB33.INBUF_EN [get_cells {btn_IBUF[3]_inst}]
set_property LOC K17 [get_cells {btn_IBUF[3]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[13]_inst}]
set_property LOC V17 [get_cells {fir_out_OBUF[13]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {Hsync_OBUF_inst}]
set_property LOC M13 [get_cells {Hsync_OBUF_inst}]
set_property BEL IOB33.OUTBUF [get_cells {vgaBlue_OBUF[2]_inst}]
set_property LOC P17 [get_cells {vgaBlue_OBUF[2]_inst}]
set_property PACKAGE_PIN T13 [get_ports {fir_out[4]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[5]_inst}]
set_property LOC V14 [get_cells {fir_out_OBUF[5]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {vgaGreen_OBUF[1]_inst}]
set_property LOC M16 [get_cells {vgaGreen_OBUF[1]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {vgaRed_OBUF[0]_inst}]
set_property LOC P14 [get_cells {vgaRed_OBUF[0]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {vgaBlue_OBUF[3]_inst}]
set_property LOC N16 [get_cells {vgaBlue_OBUF[3]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[19]_inst}]
set_property LOC T16 [get_cells {fir_out_OBUF[19]_inst}]
set_property PACKAGE_PIN P14 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN R16 [get_ports {fir_out[20]}]
set_property PACKAGE_PIN R12 [get_ports {sw[1]}]
set_property BEL IOB33.INBUF_EN [get_cells {sw_IBUF[0]_inst}]
set_property LOC R13 [get_cells {sw_IBUF[0]_inst}]
set_property PACKAGE_PIN K17 [get_ports {btn[3]}]
set_property PACKAGE_PIN V14 [get_ports {fir_out[5]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[16]_inst}]
set_property LOC U17 [get_cells {fir_out_OBUF[16]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[21]_inst}]
set_property LOC T15 [get_cells {fir_out_OBUF[21]_inst}]
set_property PACKAGE_PIN N14 [get_ports {vgaRed[1]}]
set_property PACKAGE_PIN T15 [get_ports {fir_out[21]}]
set_property PACKAGE_PIN M18 [get_ports {sw[2]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[3]_inst}]
set_property LOC U13 [get_cells {fir_out_OBUF[3]_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[0]_inst}]
set_property LOC R10 [get_cells {fir_out_OBUF[0]_inst}]
set_property PACKAGE_PIN U14 [get_ports {fir_out[6]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[17]_inst}]
set_property LOC V16 [get_cells {fir_out_OBUF[17]_inst}]
set_property PACKAGE_PIN T18 [get_ports {vgaRed[2]}]
set_property PACKAGE_PIN L18 [get_ports {sw[3]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[23]_inst}]
set_property LOC R15 [get_cells {fir_out_OBUF[23]_inst}]
set_property PACKAGE_PIN V11 [get_ports {fir_out[7]}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[1]_inst}]
set_property LOC T10 [get_cells {fir_out_OBUF[1]_inst}]
set_property PACKAGE_PIN R18 [get_ports {vgaRed[3]}]
set_property PACKAGE_PIN L16 [get_ports {sw[4]}]
set_property BEL RAMB36E1.RAMB36E1 [get_cells {cg/mem/char_ram_reg}]
set_property LOC RAMB36_X0Y18 [get_cells {cg/mem/char_ram_reg}]
set_property BEL IOB33.INBUF_EN [get_cells {btn_IBUF[0]_inst}]
set_property LOC K18 [get_cells {btn_IBUF[0]_inst}]
set_property PACKAGE_PIN L15 [get_ports {sw[5]}]
set_property PACKAGE_PIN V10 [get_ports {fir_out[8]}]
set_property BEL IOB33.OUTBUF [get_cells {Vsync_OBUF_inst}]
set_property LOC L13 [get_cells {Vsync_OBUF_inst}]
set_property BEL IOB33.OUTBUF [get_cells {fir_out_OBUF[22]_inst}]
set_property LOC T14 [get_cells {fir_out_OBUF[22]_inst}]
set_property BEL SLICEM.D6LUT [get_cells {rapidSmithRoutethrough77}]
set_property LOC SLICE_X12Y54 [get_cells {rapidSmithRoutethrough77}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough77}]
set_property BEL SLICEM.D6LUT [get_cells {vs_dd_reg_srl2_i_1}]
set_property LOC SLICE_X8Y92 [get_cells {vs_dd_reg_srl2_i_1}]
set_property LOCK_PINS { I0:A5 I1:A4 I2:A2 I3:A3 I4:A6 I5:A1 } [get_cells {vs_dd_reg_srl2_i_1}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough67}]
set_property LOC SLICE_X13Y53 [get_cells {rapidSmithRoutethrough67}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough67}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough73}]
set_property LOC SLICE_X13Y56 [get_cells {rapidSmithRoutethrough73}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough73}]
set_property BEL SLICEM.D6LUT [get_cells {rapidSmithRoutethrough55}]
set_property LOC SLICE_X12Y56 [get_cells {rapidSmithRoutethrough55}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough55}]
set_property BEL SLICEM.D6LUT [get_cells {rapidSmithRoutethrough56}]
set_property LOC SLICE_X12Y59 [get_cells {rapidSmithRoutethrough56}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough56}]
set_property BEL SLICEM.D6LUT [get_cells {rapidSmithRoutethrough61}]
set_property LOC SLICE_X12Y53 [get_cells {rapidSmithRoutethrough61}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough61}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough45}]
set_property LOC SLICE_X13Y59 [get_cells {rapidSmithRoutethrough45}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough45}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough47}]
set_property LOC SLICE_X13Y62 [get_cells {rapidSmithRoutethrough47}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough47}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough51}]
set_property LOC SLICE_X13Y52 [get_cells {rapidSmithRoutethrough51}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough51}]
set_property BEL SLICEM.D6LUT [get_cells {rapidSmithRoutethrough0}]
set_property LOC SLICE_X12Y57 [get_cells {rapidSmithRoutethrough0}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough0}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough39}]
set_property LOC SLICE_X13Y61 [get_cells {rapidSmithRoutethrough39}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough39}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough38}]
set_property LOC SLICE_X13Y58 [get_cells {rapidSmithRoutethrough38}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough38}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough36}]
set_property LOC SLICE_X13Y55 [get_cells {rapidSmithRoutethrough36}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough36}]
set_property BEL SLICEM.D6LUT [get_cells {rapidSmithRoutethrough22}]
set_property LOC SLICE_X12Y58 [get_cells {rapidSmithRoutethrough22}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough22}]
set_property BEL SLICEM.D6LUT [get_cells {rapidSmithRoutethrough21}]
set_property LOC SLICE_X12Y55 [get_cells {rapidSmithRoutethrough21}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough21}]
set_property BEL SLICEM.D6LUT [get_cells {h_counter[9]_i_3}]
set_property LOC SLICE_X6Y91 [get_cells {h_counter[9]_i_3}]
set_property LOCK_PINS { I0:A4 I1:A5 I2:A2 I3:A3 } [get_cells {h_counter[9]_i_3}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough17}]
set_property LOC SLICE_X13Y63 [get_cells {rapidSmithRoutethrough17}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough17}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough16}]
set_property LOC SLICE_X13Y60 [get_cells {rapidSmithRoutethrough16}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough16}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough19}]
set_property LOC SLICE_X13Y54 [get_cells {rapidSmithRoutethrough19}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough19}]
set_property BEL SLICEL.D6LUT [get_cells {rapidSmithRoutethrough15}]
set_property LOC SLICE_X13Y57 [get_cells {rapidSmithRoutethrough15}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough15}]
set_property BEL SLICEM.D6LUT [get_cells {v_counter[9]_i_4}]
set_property LOC SLICE_X8Y91 [get_cells {v_counter[9]_i_4}]
set_property LOCK_PINS { I0:A5 I1:A3 I2:A2 I3:A1 I4:A4 } [get_cells {v_counter[9]_i_4}]
set_property BEL SLICEM.D6LUT [get_cells {v_counter[9]_i_1}]
set_property LOC SLICE_X6Y90 [get_cells {v_counter[9]_i_1}]
set_property LOCK_PINS { I0:A1 I1:A4 } [get_cells {v_counter[9]_i_1}]
set_property BEL SLICEM.D6LUT [get_cells {char_y_addr[4]_i_1}]
set_property LOC SLICE_X8Y90 [get_cells {char_y_addr[4]_i_1}]
set_property LOCK_PINS { I0:A2 I1:A5 I2:A6 I3:A1 I4:A3 I5:A4 } [get_cells {char_y_addr[4]_i_1}]
set_property BEL SLICEM.B6LUT [get_cells {v_counter[1]_i_1}]
set_property LOC SLICE_X8Y93 [get_cells {v_counter[1]_i_1}]
set_property LOCK_PINS { I0:A3 I1:A2 } [get_cells {v_counter[1]_i_1}]
set_property BEL SLICEL.A6LUT [get_cells {btn_counter[0]_i_5}]
set_property LOC SLICE_X13Y52 [get_cells {btn_counter[0]_i_5}]
set_property LOCK_PINS { I0:A3 } [get_cells {btn_counter[0]_i_5}]
set_property BEL SLICEL.A6LUT [get_cells {char_x_addr[1]_i_1}]
set_property LOC SLICE_X9Y90 [get_cells {char_x_addr[1]_i_1}]
set_property LOCK_PINS { I0:A2 I1:A3 } [get_cells {char_x_addr[1]_i_1}]
set_property BEL SLICEM.A6LUT [get_cells {char_y_addr[1]_i_1}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr[1]_i_1}]
set_property LOCK_PINS { I0:A1 I1:A3 } [get_cells {char_y_addr[1]_i_1}]
set_property BEL SLICEM.B6LUT [get_cells {hs_dd_reg_srl2_i_1}]
set_property LOC SLICE_X6Y90 [get_cells {hs_dd_reg_srl2_i_1}]
set_property LOCK_PINS { I0:A5 I1:A6 I2:A2 I3:A4 I4:A1 I5:A3 } [get_cells {hs_dd_reg_srl2_i_1}]
set_property BEL SLICEM.A5LUT [get_cells {v_counter[3]_i_1}]
set_property LOC SLICE_X8Y93 [get_cells {v_counter[3]_i_1}]
set_property LOCK_PINS { I0:A1 I1:A2 I2:A4 I3:A3 I4:A5 } [get_cells {v_counter[3]_i_1}]
set_property BEL SLICEM.C6LUT [get_cells {h_counter[6]_i_1}]
set_property LOC SLICE_X6Y91 [get_cells {h_counter[6]_i_1}]
set_property LOCK_PINS { I0:A2 I1:A6 I2:A3 I3:A1 } [get_cells {h_counter[6]_i_1}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough75}]
set_property LOC SLICE_X13Y54 [get_cells {rapidSmithRoutethrough75}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough75}]
set_property BEL SLICEM.A6LUT [get_cells {rapidSmithRoutethrough74}]
set_property LOC SLICE_X12Y55 [get_cells {rapidSmithRoutethrough74}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough74}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough76}]
set_property LOC SLICE_X13Y54 [get_cells {rapidSmithRoutethrough76}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough76}]
set_property BEL SLICEM.C6LUT [get_cells {char_x_addr[5]_i_1}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr[5]_i_1}]
set_property LOCK_PINS { I0:A4 I1:A5 I2:A6 I3:A1 I4:A3 I5:A2 } [get_cells {char_x_addr[5]_i_1}]
set_property BEL SLICEM.A6LUT [get_cells {rapidSmithRoutethrough64}]
set_property LOC SLICE_X12Y60 [get_cells {rapidSmithRoutethrough64}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough64}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough63}]
set_property LOC SLICE_X13Y56 [get_cells {rapidSmithRoutethrough63}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough63}]
set_property BEL SLICEM.C6LUT [get_cells {rapidSmithRoutethrough66}]
set_property LOC SLICE_X12Y54 [get_cells {rapidSmithRoutethrough66}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough66}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough65}]
set_property LOC SLICE_X13Y59 [get_cells {rapidSmithRoutethrough65}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough65}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough68}]
set_property LOC SLICE_X13Y56 [get_cells {rapidSmithRoutethrough68}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough68}]
set_property BEL SLICEM.B6LUT [get_cells {rapidSmithRoutethrough69}]
set_property LOC SLICE_X12Y57 [get_cells {rapidSmithRoutethrough69}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough69}]
set_property BEL SLICEM.B6LUT [get_cells {rapidSmithRoutethrough71}]
set_property LOC SLICE_X12Y54 [get_cells {rapidSmithRoutethrough71}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough71}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough70}]
set_property LOC SLICE_X13Y53 [get_cells {rapidSmithRoutethrough70}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough70}]
set_property BEL SLICEM.C6LUT [get_cells {rapidSmithRoutethrough72}]
set_property LOC SLICE_X12Y57 [get_cells {rapidSmithRoutethrough72}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough72}]
set_property BEL SLICEM.B6LUT [get_cells {char_x_addr[4]_i_1}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr[4]_i_1}]
set_property LOCK_PINS { I0:A5 I1:A1 I2:A3 I3:A2 } [get_cells {char_x_addr[4]_i_1}]
set_property BEL SLICEM.B6LUT [get_cells {rapidSmithRoutethrough53}]
set_property LOC SLICE_X12Y53 [get_cells {rapidSmithRoutethrough53}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough53}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough52}]
set_property LOC SLICE_X13Y52 [get_cells {rapidSmithRoutethrough52}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough52}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough54}]
set_property LOC SLICE_X13Y56 [get_cells {rapidSmithRoutethrough54}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough54}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough57}]
set_property LOC SLICE_X13Y59 [get_cells {rapidSmithRoutethrough57}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough57}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough59}]
set_property LOC SLICE_X13Y53 [get_cells {rapidSmithRoutethrough59}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough59}]
set_property BEL SLICEM.A6LUT [get_cells {rapidSmithRoutethrough58}]
set_property LOC SLICE_X12Y54 [get_cells {rapidSmithRoutethrough58}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough58}]
set_property BEL SLICEM.B5LUT [get_cells {vs_dd_reg_srl2}]
set_property LOC SLICE_X2Y87 [get_cells {vs_dd_reg_srl2}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough60}]
set_property LOC SLICE_X13Y53 [get_cells {rapidSmithRoutethrough60}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough60}]
set_property BEL SLICEM.A6LUT [get_cells {rapidSmithRoutethrough62}]
set_property LOC SLICE_X12Y57 [get_cells {rapidSmithRoutethrough62}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough62}]
set_property BEL SLICEM.A5LUT [get_cells {h_counter[4]_i_1}]
set_property LOC SLICE_X6Y92 [get_cells {h_counter[4]_i_1}]
set_property LOCK_PINS { I0:A4 I1:A5 I2:A1 I3:A2 I4:A3 } [get_cells {h_counter[4]_i_1}]
set_property BEL SLICEM.C6LUT [get_cells {v_counter[5]_i_1}]
set_property LOC SLICE_X8Y92 [get_cells {v_counter[5]_i_1}]
set_property LOCK_PINS { I0:A2 I1:A1 I2:A6 I3:A3 I4:A4 I5:A5 } [get_cells {v_counter[5]_i_1}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough49}]
set_property LOC SLICE_X13Y52 [get_cells {rapidSmithRoutethrough49}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough49}]
set_property BEL SLICEM.B6LUT [get_cells {rapidSmithRoutethrough42}]
set_property LOC SLICE_X12Y60 [get_cells {rapidSmithRoutethrough42}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough42}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough41}]
set_property LOC SLICE_X13Y62 [get_cells {rapidSmithRoutethrough41}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough41}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough44}]
set_property LOC SLICE_X13Y62 [get_cells {rapidSmithRoutethrough44}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough44}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough43}]
set_property LOC SLICE_X13Y59 [get_cells {rapidSmithRoutethrough43}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough43}]
set_property BEL SLICEM.C6LUT [get_cells {rapidSmithRoutethrough46}]
set_property LOC SLICE_X12Y60 [get_cells {rapidSmithRoutethrough46}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough46}]
set_property BEL SLICEM.A6LUT [get_cells {rapidSmithRoutethrough48}]
set_property LOC SLICE_X12Y53 [get_cells {rapidSmithRoutethrough48}]
set_property LOCK_PINS { I0:A5 } [get_cells {rapidSmithRoutethrough48}]
set_property BEL SLICEM.A6LUT [get_cells {char_x_addr[3]_i_1}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr[3]_i_1}]
set_property LOCK_PINS { I0:A1 I1:A4 I2:A5 I3:A3 } [get_cells {char_x_addr[3]_i_1}]
set_property BEL SLICEM.B6LUT [get_cells {v_counter[4]_i_1}]
set_property LOC SLICE_X8Y92 [get_cells {v_counter[4]_i_1}]
set_property LOCK_PINS { I0:A5 I1:A2 I2:A3 I3:A4 I4:A1 } [get_cells {v_counter[4]_i_1}]
set_property BEL SLICEM.C6LUT [get_cells {rapidSmithRoutethrough50}]
set_property LOC SLICE_X12Y53 [get_cells {rapidSmithRoutethrough50}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough50}]
set_property BEL SLICEM.A6LUT [get_cells {h_counter[5]_i_1}]
set_property LOC SLICE_X6Y90 [get_cells {h_counter[5]_i_1}]
set_property LOCK_PINS { I0:A1 I1:A5 I2:A6 I3:A2 I4:A3 I5:A4 } [get_cells {h_counter[5]_i_1}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough2}]
set_property LOC SLICE_X13Y60 [get_cells {rapidSmithRoutethrough2}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough2}]
set_property BEL SLICEM.A6LUT [get_cells {h_counter[5]_i_2}]
set_property LOC SLICE_X6Y92 [get_cells {h_counter[5]_i_2}]
set_property LOCK_PINS { I0:A5 I1:A1 I2:A2 I3:A3 I4:A4 } [get_cells {h_counter[5]_i_2}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough1}]
set_property LOC SLICE_X13Y57 [get_cells {rapidSmithRoutethrough1}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough1}]
set_property BEL SLICEM.B6LUT [get_cells {rapidSmithRoutethrough31}]
set_property LOC SLICE_X12Y56 [get_cells {rapidSmithRoutethrough31}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough31}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough30}]
set_property LOC SLICE_X13Y55 [get_cells {rapidSmithRoutethrough30}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough30}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough33}]
set_property LOC SLICE_X13Y58 [get_cells {rapidSmithRoutethrough33}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough33}]
set_property BEL SLICEL.A6LUT [get_cells {pixel_en_i_1}]
set_property LOC SLICE_X7Y90 [get_cells {pixel_en_i_1}]
set_property LOCK_PINS { I0:A3 } [get_cells {pixel_en_i_1}]
set_property BEL SLICEM.B6LUT [get_cells {rapidSmithRoutethrough32}]
set_property LOC SLICE_X12Y59 [get_cells {rapidSmithRoutethrough32}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough32}]
set_property BEL SLICEM.C6LUT [get_cells {rapidSmithRoutethrough35}]
set_property LOC SLICE_X12Y56 [get_cells {rapidSmithRoutethrough35}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough35}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough34}]
set_property LOC SLICE_X13Y61 [get_cells {rapidSmithRoutethrough34}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough34}]
set_property BEL SLICEM.C6LUT [get_cells {rapidSmithRoutethrough37}]
set_property LOC SLICE_X12Y59 [get_cells {rapidSmithRoutethrough37}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough37}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough40}]
set_property LOC SLICE_X13Y62 [get_cells {rapidSmithRoutethrough40}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough40}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough8}]
set_property LOC SLICE_X13Y60 [get_cells {rapidSmithRoutethrough8}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough8}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough7}]
set_property LOC SLICE_X13Y60 [get_cells {rapidSmithRoutethrough7}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough7}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough9}]
set_property LOC SLICE_X13Y63 [get_cells {rapidSmithRoutethrough9}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough9}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough4}]
set_property LOC SLICE_X13Y63 [get_cells {rapidSmithRoutethrough4}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough4}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough3}]
set_property LOC SLICE_X13Y63 [get_cells {rapidSmithRoutethrough3}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough3}]
set_property BEL SLICEM.A6LUT [get_cells {rapidSmithRoutethrough6}]
set_property LOC SLICE_X12Y58 [get_cells {rapidSmithRoutethrough6}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough6}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough5}]
set_property LOC SLICE_X13Y57 [get_cells {rapidSmithRoutethrough5}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough5}]
set_property BEL SLICEM.A6LUT [get_cells {rapidSmithRoutethrough28}]
set_property LOC SLICE_X12Y59 [get_cells {rapidSmithRoutethrough28}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough28}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough27}]
set_property LOC SLICE_X13Y58 [get_cells {rapidSmithRoutethrough27}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough27}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough29}]
set_property LOC SLICE_X13Y61 [get_cells {rapidSmithRoutethrough29}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough29}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough20}]
set_property LOC SLICE_X13Y55 [get_cells {rapidSmithRoutethrough20}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough20}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough24}]
set_property LOC SLICE_X13Y61 [get_cells {rapidSmithRoutethrough24}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough24}]
set_property BEL SLICEL.A6LUT [get_cells {rapidSmithRoutethrough23}]
set_property LOC SLICE_X13Y58 [get_cells {rapidSmithRoutethrough23}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough23}]
set_property BEL SLICEL.B6LUT [get_cells {rapidSmithRoutethrough26}]
set_property LOC SLICE_X13Y55 [get_cells {rapidSmithRoutethrough26}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough26}]
set_property BEL SLICEM.A6LUT [get_cells {rapidSmithRoutethrough25}]
set_property LOC SLICE_X12Y56 [get_cells {rapidSmithRoutethrough25}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough25}]
set_property BEL SLICEL.B6LUT [get_cells {char_x_addr[0]_i_1}]
set_property LOC SLICE_X9Y90 [get_cells {char_x_addr[0]_i_1}]
set_property LOCK_PINS { I0:A2 } [get_cells {char_x_addr[0]_i_1}]
set_property BEL SLICEM.A5LUT [get_cells {h_counter[9]_i_4}]
set_property LOC SLICE_X6Y91 [get_cells {h_counter[9]_i_4}]
set_property LOCK_PINS { I0:A1 I1:A2 I2:A5 I3:A3 } [get_cells {h_counter[9]_i_4}]
set_property BEL SLICEM.C6LUT [get_cells {h_counter[9]_i_5}]
set_property LOC SLICE_X6Y92 [get_cells {h_counter[9]_i_5}]
set_property LOCK_PINS { I0:A1 I1:A3 I2:A4 I3:A2 } [get_cells {h_counter[9]_i_5}]
set_property BEL SLICEM.C6LUT [get_cells {char_y_addr[0]_i_1}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr[0]_i_1}]
set_property LOCK_PINS { I0:A2 } [get_cells {char_y_addr[0]_i_1}]
set_property BEL SLICEL.A5LUT [get_cells {h_counter[9]_i_1}]
set_property LOC SLICE_X7Y91 [get_cells {h_counter[9]_i_1}]
set_property LOCK_PINS { I0:A4 I1:A3 I2:A5 I3:A2 } [get_cells {h_counter[9]_i_1}]
set_property BEL SLICEM.B5LUT [get_cells {h_counter[9]_i_2}]
set_property LOC SLICE_X6Y91 [get_cells {h_counter[9]_i_2}]
set_property LOCK_PINS { I0:A4 I1:A1 I2:A5 I3:A3 I4:A2 } [get_cells {h_counter[9]_i_2}]
set_property BEL SLICEM.A6LUT [get_cells {v_counter[0]_i_1}]
set_property LOC SLICE_X8Y92 [get_cells {v_counter[0]_i_1}]
set_property LOCK_PINS { I0:A3 I1:A1 } [get_cells {v_counter[0]_i_1}]
set_property BEL SLICEM.C6LUT [get_cells {rapidSmithRoutethrough18}]
set_property LOC SLICE_X12Y55 [get_cells {rapidSmithRoutethrough18}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough18}]
set_property BEL SLICEL.A6LUT [get_cells {vgaRed[3]_i_4}]
set_property LOC SLICE_X7Y95 [get_cells {vgaRed[3]_i_4}]
set_property LOCK_PINS { I0:A4 I1:A5 I2:A6 I3:A2 I4:A3 I5:A1 } [get_cells {vgaRed[3]_i_4}]
set_property BEL SLICEL.B6LUT [get_cells {vgaRed[3]_i_3}]
set_property LOC SLICE_X7Y95 [get_cells {vgaRed[3]_i_3}]
set_property LOCK_PINS { I0:A4 I1:A1 I2:A6 I3:A5 I4:A3 I5:A2 } [get_cells {vgaRed[3]_i_3}]
set_property BEL SLICEM.B6LUT [get_cells {rapidSmithRoutethrough11}]
set_property LOC SLICE_X12Y55 [get_cells {rapidSmithRoutethrough11}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough11}]
set_property BEL SLICEL.A6LUT [get_cells {vgaRed[3]_i_1}]
set_property LOC SLICE_X7Y92 [get_cells {vgaRed[3]_i_1}]
set_property LOCK_PINS { I0:A1 I1:A3 I2:A2 I3:A5 I4:A6 I5:A4 } [get_cells {vgaRed[3]_i_1}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough10}]
set_property LOC SLICE_X13Y54 [get_cells {rapidSmithRoutethrough10}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough10}]
set_property BEL SLICEL.C6LUT [get_cells {rapidSmithRoutethrough13}]
set_property LOC SLICE_X13Y57 [get_cells {rapidSmithRoutethrough13}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough13}]
set_property BEL SLICEM.B6LUT [get_cells {rapidSmithRoutethrough12}]
set_property LOC SLICE_X12Y58 [get_cells {rapidSmithRoutethrough12}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough12}]
set_property BEL SLICEM.C6LUT [get_cells {rapidSmithRoutethrough14}]
set_property LOC SLICE_X12Y58 [get_cells {rapidSmithRoutethrough14}]
set_property LOCK_PINS { I0:A6 } [get_cells {rapidSmithRoutethrough14}]
set_property BEL SLICEM.B6LUT [get_cells {h_counter[7]_i_1}]
set_property LOC SLICE_X6Y91 [get_cells {h_counter[7]_i_1}]
set_property LOCK_PINS { I0:A4 I1:A1 I2:A5 I3:A3 I4:A2 } [get_cells {h_counter[7]_i_1}]
set_property BEL SLICEM.B6LUT [get_cells {h_counter[7]_i_2}]
set_property LOC SLICE_X6Y92 [get_cells {h_counter[7]_i_2}]
set_property LOCK_PINS { I0:A3 I1:A2 I2:A1 I3:A5 } [get_cells {h_counter[7]_i_2}]
set_property BEL SLICEM.A6LUT [get_cells {v_counter[2]_i_1}]
set_property LOC SLICE_X8Y93 [get_cells {v_counter[2]_i_1}]
set_property LOCK_PINS { I0:A3 I1:A4 I2:A2 } [get_cells {v_counter[2]_i_1}]
set_property BEL SLICEM.C6LUT [get_cells {v_counter[9]_i_7}]
set_property LOC SLICE_X8Y91 [get_cells {v_counter[9]_i_7}]
set_property LOCK_PINS { I0:A3 I1:A5 I2:A4 I3:A2 I4:A1 I5:A6 } [get_cells {v_counter[9]_i_7}]
set_property BEL SLICEM.B5LUT [get_cells {v_counter[9]_i_5}]
set_property LOC SLICE_X8Y92 [get_cells {v_counter[9]_i_5}]
set_property LOCK_PINS { I0:A5 I1:A2 I2:A3 I3:A4 I4:A1 } [get_cells {v_counter[9]_i_5}]
set_property BEL SLICEM.B5LUT [get_cells {v_counter[9]_i_6}]
set_property LOC SLICE_X8Y91 [get_cells {v_counter[9]_i_6}]
set_property LOCK_PINS { I0:A3 I1:A2 I2:A5 I3:A4 } [get_cells {v_counter[9]_i_6}]
set_property BEL SLICEM.C6LUT [get_cells {v_counter[9]_i_3}]
set_property LOC SLICE_X6Y90 [get_cells {v_counter[9]_i_3}]
set_property LOCK_PINS { I0:A6 I1:A3 I2:A4 I3:A1 I4:A2 I5:A5 } [get_cells {v_counter[9]_i_3}]
set_property BEL SLICEL.B6LUT [get_cells {h_counter[0]_i_1}]
set_property LOC SLICE_X7Y91 [get_cells {h_counter[0]_i_1}]
set_property LOCK_PINS { I0:A2 } [get_cells {h_counter[0]_i_1}]
set_property BEL SLICEM.A5LUT [get_cells {v_counter[9]_i_2}]
set_property LOC SLICE_X8Y92 [get_cells {v_counter[9]_i_2}]
set_property LOCK_PINS { I0:A1 I1:A5 I2:A2 I3:A4 } [get_cells {v_counter[9]_i_2}]
set_property BEL SLICEL.B6LUT [get_cells {btn_debounce_d_i_1}]
set_property LOC SLICE_X9Y73 [get_cells {btn_debounce_d_i_1}]
set_property LOCK_PINS { I0:A1 I1:A5 I2:A4 I3:A3 I4:A2 } [get_cells {btn_debounce_d_i_1}]
set_property BEL SLICEL.A5LUT [get_cells {char_x_addr[2]_i_1}]
set_property LOC SLICE_X9Y90 [get_cells {char_x_addr[2]_i_1}]
set_property LOCK_PINS { I0:A3 I1:A2 I2:A4 } [get_cells {char_x_addr[2]_i_1}]
set_property BEL SLICEM.A5LUT [get_cells {char_y_addr[2]_i_1}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr[2]_i_1}]
set_property LOCK_PINS { I0:A3 I1:A1 I2:A5 } [get_cells {char_y_addr[2]_i_1}]
set_property BEL SLICEM.A6LUT [get_cells {v_counter[6]_i_1}]
set_property LOC SLICE_X8Y91 [get_cells {v_counter[6]_i_1}]
set_property LOCK_PINS { I0:A3 I1:A1 I2:A2 } [get_cells {v_counter[6]_i_1}]
set_property BEL SLICEM.C5LUT [get_cells {h_counter[3]_i_1}]
set_property LOC SLICE_X6Y92 [get_cells {h_counter[3]_i_1}]
set_property LOCK_PINS { I0:A4 I1:A5 I2:A2 I3:A1 } [get_cells {h_counter[3]_i_1}]
set_property BEL SLICEM.A5LUT [get_cells {v_counter[7]_i_1}]
set_property LOC SLICE_X8Y91 [get_cells {v_counter[7]_i_1}]
set_property LOCK_PINS { I0:A5 I1:A1 I2:A2 I3:A3 } [get_cells {v_counter[7]_i_1}]
set_property BEL SLICEM.B6LUT [get_cells {accum_reg_i_9}]
set_property LOC SLICE_X14Y53 [get_cells {accum_reg_i_9}]
set_property LOCK_PINS { I0:A3 } [get_cells {accum_reg_i_9}]
set_property BEL SLICEM.B5LUT [get_cells {char_y_addr[4]_i_2}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr[4]_i_2}]
set_property LOCK_PINS { I0:A2 I1:A3 I2:A4 I3:A5 I4:A1 } [get_cells {char_y_addr[4]_i_2}]
set_property BEL SLICEM.B5LUT [get_cells {char_x_addr[6]_i_1}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr[6]_i_1}]
set_property LOCK_PINS { I0:A1 I1:A3 I2:A2 I3:A5 } [get_cells {char_x_addr[6]_i_1}]
set_property BEL SLICEM.A5LUT [get_cells {char_x_addr[6]_i_2}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr[6]_i_2}]
set_property LOCK_PINS { I0:A1 I1:A4 I2:A5 I3:A3 } [get_cells {char_x_addr[6]_i_2}]
set_property BEL SLICEM.B6LUT [get_cells {v_counter[8]_i_1}]
set_property LOC SLICE_X8Y91 [get_cells {v_counter[8]_i_1}]
set_property LOCK_PINS { I0:A4 I1:A3 I2:A2 I3:A1 I4:A5 } [get_cells {v_counter[8]_i_1}]
set_property BEL SLICEM.A6LUT [get_cells {h_counter[1]_i_1}]
set_property LOC SLICE_X6Y91 [get_cells {h_counter[1]_i_1}]
set_property LOCK_PINS { I0:A4 I1:A2 } [get_cells {h_counter[1]_i_1}]
set_property BEL SLICEM.A5LUT [get_cells {hs_dd_reg_srl2}]
set_property LOC SLICE_X2Y87 [get_cells {hs_dd_reg_srl2}]
set_property BEL SLICEM.B6LUT [get_cells {char_y_addr[3]_i_1}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr[3]_i_1}]
set_property LOCK_PINS { I0:A5 I1:A4 I2:A3 I3:A2 } [get_cells {char_y_addr[3]_i_1}]
set_property BEL SLICEL.C6LUT [get_cells {char_ram_reg_i_1}]
set_property LOC SLICE_X9Y90 [get_cells {char_ram_reg_i_1}]
set_property LOCK_PINS { I0:A1 I1:A2 } [get_cells {char_ram_reg_i_1}]
set_property BEL SLICEL.A6LUT [get_cells {h_counter[8]_i_1}]
set_property LOC SLICE_X7Y91 [get_cells {h_counter[8]_i_1}]
set_property LOCK_PINS { I0:A2 I1:A4 I2:A3 } [get_cells {h_counter[8]_i_1}]
set_property BEL SLICEM.B5LUT [get_cells {h_counter[2]_i_1}]
set_property LOC SLICE_X6Y92 [get_cells {h_counter[2]_i_1}]
set_property LOCK_PINS { I0:A3 I1:A2 I2:A1 } [get_cells {h_counter[2]_i_1}]
set_property BEL SLICEM.A6LUT [get_cells {btn_Debounce_i_6}]
set_property LOC SLICE_X14Y56 [get_cells {btn_Debounce_i_6}]
set_property LOCK_PINS { I0:A6 I1:A1 I2:A3 I3:A2 I4:A5 I5:A4 } [get_cells {btn_Debounce_i_6}]
set_property BEL SLICEM.B6LUT [get_cells {btn_Debounce_i_5}]
set_property LOC SLICE_X14Y57 [get_cells {btn_Debounce_i_5}]
set_property LOCK_PINS { I0:A4 I1:A3 I2:A2 I3:A5 I4:A6 I5:A1 } [get_cells {btn_Debounce_i_5}]
set_property BEL SLICEM.A6LUT [get_cells {btn_Debounce_i_8}]
set_property LOC SLICE_X14Y58 [get_cells {btn_Debounce_i_8}]
set_property LOCK_PINS { I0:A1 I1:A6 I2:A4 I3:A3 I4:A2 I5:A5 } [get_cells {btn_Debounce_i_8}]
set_property BEL SLICEM.A6LUT [get_cells {btn_Debounce_i_7}]
set_property LOC SLICE_X14Y60 [get_cells {btn_Debounce_i_7}]
set_property LOCK_PINS { I0:A4 I1:A5 I2:A2 I3:A3 I4:A6 I5:A1 } [get_cells {btn_Debounce_i_7}]
set_property BEL SLICEM.A6LUT [get_cells {btn_Debounce_i_2}]
set_property LOC SLICE_X12Y61 [get_cells {btn_Debounce_i_2}]
set_property LOCK_PINS { I0:A2 I1:A3 I2:A5 I3:A4 I4:A1 I5:A6 } [get_cells {btn_Debounce_i_2}]
set_property BEL SLICEL.A6LUT [get_cells {btn_Debounce_i_1}]
set_property LOC SLICE_X9Y73 [get_cells {btn_Debounce_i_1}]
set_property LOCK_PINS { I0:A2 I1:A1 I2:A4 I3:A5 I4:A3 } [get_cells {btn_Debounce_i_1}]
set_property BEL SLICEM.A6LUT [get_cells {btn_Debounce_i_4}]
set_property LOC SLICE_X14Y57 [get_cells {btn_Debounce_i_4}]
set_property LOCK_PINS { I0:A4 I1:A3 I2:A2 I3:A6 I4:A1 I5:A5 } [get_cells {btn_Debounce_i_4}]
set_property BEL SLICEM.A6LUT [get_cells {btn_Debounce_i_3}]
set_property LOC SLICE_X12Y63 [get_cells {btn_Debounce_i_3}]
set_property LOCK_PINS { I0:A5 I1:A4 I2:A3 I3:A1 I4:A2 I5:A6 } [get_cells {btn_Debounce_i_3}]
set_property BEL SLICEM.A6LUT [get_cells {btn_Debounce_i_9}]
set_property LOC SLICE_X14Y54 [get_cells {btn_Debounce_i_9}]
set_property LOCK_PINS { I0:A4 I1:A5 I2:A2 I3:A3 I4:A6 I5:A1 } [get_cells {btn_Debounce_i_9}]
set_property BEL SLICEM.A6LUT [get_cells {btn_Debounce_i_10}]
set_property LOC SLICE_X14Y53 [get_cells {btn_Debounce_i_10}]
set_property LOCK_PINS { I0:A6 I1:A1 I2:A3 I3:A2 I4:A5 I5:A4 } [get_cells {btn_Debounce_i_10}]
set_property BEL SLICEL.BFF [get_cells {btn_debounce_d_reg}]
set_property LOC SLICE_X9Y73 [get_cells {btn_debounce_d_reg}]
set_property BEL SLICEL.AFF [get_cells {cg/pixel_x_d_reg[1]}]
set_property LOC SLICE_X7Y94 [get_cells {cg/pixel_x_d_reg[1]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[20]}]
set_property LOC SLICE_X13Y57 [get_cells {btn_counter_reg[20]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[32]}]
set_property LOC SLICE_X13Y60 [get_cells {btn_counter_reg[32]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[44]}]
set_property LOC SLICE_X13Y63 [get_cells {btn_counter_reg[44]}]
set_property BEL SLICEL.DFF [get_cells {cg/pixel_x_dd_reg[2]}]
set_property LOC SLICE_X7Y94 [get_cells {cg/pixel_x_dd_reg[2]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[45]}]
set_property LOC SLICE_X13Y63 [get_cells {btn_counter_reg[45]}]
set_property BEL SLICEL.AFF [get_cells {vt/pixel_en_reg}]
set_property LOC SLICE_X7Y90 [get_cells {vt/pixel_en_reg}]
set_property BEL SLICEM.AFF [get_cells {cg/pixel_x_d_reg[2]}]
set_property LOC SLICE_X6Y92 [get_cells {cg/pixel_x_d_reg[2]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[21]}]
set_property LOC SLICE_X13Y57 [get_cells {btn_counter_reg[21]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[33]}]
set_property LOC SLICE_X13Y60 [get_cells {btn_counter_reg[33]}]
set_property BEL SLICEL.CFF [get_cells {cg/pixel_x_dd_reg[1]}]
set_property LOC SLICE_X7Y94 [get_cells {cg/pixel_x_dd_reg[1]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[34]}]
set_property LOC SLICE_X13Y60 [get_cells {btn_counter_reg[34]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[46]}]
set_property LOC SLICE_X13Y63 [get_cells {btn_counter_reg[46]}]
set_property BEL SLICEL.BFF [get_cells {cg/pixel_x_dd_reg[0]}]
set_property LOC SLICE_X7Y94 [get_cells {cg/pixel_x_dd_reg[0]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[10]}]
set_property LOC SLICE_X13Y54 [get_cells {btn_counter_reg[10]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[22]}]
set_property LOC SLICE_X13Y57 [get_cells {btn_counter_reg[22]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[23]}]
set_property LOC SLICE_X13Y57 [get_cells {btn_counter_reg[23]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[35]}]
set_property LOC SLICE_X13Y60 [get_cells {btn_counter_reg[35]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[47]}]
set_property LOC SLICE_X13Y63 [get_cells {btn_counter_reg[47]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[11]}]
set_property LOC SLICE_X13Y54 [get_cells {btn_counter_reg[11]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[1]}]
set_property LOC SLICE_X13Y52 [get_cells {btn_counter_reg[1]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[12]}]
set_property LOC SLICE_X13Y55 [get_cells {btn_counter_reg[12]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[24]}]
set_property LOC SLICE_X13Y58 [get_cells {btn_counter_reg[24]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[36]}]
set_property LOC SLICE_X13Y61 [get_cells {btn_counter_reg[36]}]
set_property BEL SLICEM.BFF [get_cells {char_y_addr_reg[3]}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr_reg[3]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[0]}]
set_property LOC SLICE_X13Y52 [get_cells {btn_counter_reg[0]}]
set_property BEL SLICEM.BFF [get_cells {vt/v_counter_reg[8]}]
set_property LOC SLICE_X8Y91 [get_cells {vt/v_counter_reg[8]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[13]}]
set_property LOC SLICE_X13Y55 [get_cells {btn_counter_reg[13]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[25]}]
set_property LOC SLICE_X13Y58 [get_cells {btn_counter_reg[25]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[37]}]
set_property LOC SLICE_X13Y61 [get_cells {btn_counter_reg[37]}]
set_property BEL SLICEM.CFF [get_cells {vt/v_counter_reg[5]}]
set_property LOC SLICE_X8Y92 [get_cells {vt/v_counter_reg[5]}]
set_property BEL SLICEM.DFF [get_cells {vt/h_counter_reg[7]}]
set_property LOC SLICE_X6Y91 [get_cells {vt/h_counter_reg[7]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[14]}]
set_property LOC SLICE_X13Y55 [get_cells {btn_counter_reg[14]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[26]}]
set_property LOC SLICE_X13Y58 [get_cells {btn_counter_reg[26]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[38]}]
set_property LOC SLICE_X13Y61 [get_cells {btn_counter_reg[38]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[3]}]
set_property LOC SLICE_X13Y52 [get_cells {btn_counter_reg[3]}]
set_property BEL SLICEM.AFF [get_cells {vt/v_counter_reg[6]}]
set_property LOC SLICE_X8Y91 [get_cells {vt/v_counter_reg[6]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[2]}]
set_property LOC SLICE_X13Y52 [get_cells {btn_counter_reg[2]}]
set_property BEL SLICEL.AFF [get_cells {vt/h_counter_reg[8]}]
set_property LOC SLICE_X7Y91 [get_cells {vt/h_counter_reg[8]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[15]}]
set_property LOC SLICE_X13Y55 [get_cells {btn_counter_reg[15]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[27]}]
set_property LOC SLICE_X13Y58 [get_cells {btn_counter_reg[27]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[39]}]
set_property LOC SLICE_X13Y61 [get_cells {btn_counter_reg[39]}]
set_property BEL SLICEM.AFF [get_cells {cg/pixel_x_d_reg[0]}]
set_property LOC SLICE_X6Y94 [get_cells {cg/pixel_x_d_reg[0]}]
set_property BEL SLICEM.AFF [get_cells {vt/h_counter_reg[5]}]
set_property LOC SLICE_X6Y90 [get_cells {vt/h_counter_reg[5]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[16]}]
set_property LOC SLICE_X13Y56 [get_cells {btn_counter_reg[16]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[28]}]
set_property LOC SLICE_X13Y59 [get_cells {btn_counter_reg[28]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[5]}]
set_property LOC SLICE_X13Y53 [get_cells {btn_counter_reg[5]}]
set_property BEL SLICEL.AFF [get_cells {btn_Debounce_reg}]
set_property LOC SLICE_X9Y73 [get_cells {btn_Debounce_reg}]
set_property BEL SLICEM.BFF [get_cells {vt/v_counter_reg[4]}]
set_property LOC SLICE_X8Y92 [get_cells {vt/v_counter_reg[4]}]
set_property BEL SLICEM.CFF [get_cells {vt/h_counter_reg[6]}]
set_property LOC SLICE_X6Y91 [get_cells {vt/h_counter_reg[6]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[4]}]
set_property LOC SLICE_X13Y53 [get_cells {btn_counter_reg[4]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[17]}]
set_property LOC SLICE_X13Y56 [get_cells {btn_counter_reg[17]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[29]}]
set_property LOC SLICE_X13Y59 [get_cells {btn_counter_reg[29]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[7]}]
set_property LOC SLICE_X13Y53 [get_cells {btn_counter_reg[7]}]
set_property BEL SLICEM.BFF [get_cells {vt/h_counter_reg[3]}]
set_property LOC SLICE_X6Y91 [get_cells {vt/h_counter_reg[3]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[18]}]
set_property LOC SLICE_X13Y56 [get_cells {btn_counter_reg[18]}]
set_property BEL SLICEL.BFF [get_cells {char_x_addr_reg[0]}]
set_property LOC SLICE_X9Y90 [get_cells {char_x_addr_reg[0]}]
set_property BEL SLICEM.AFF [get_cells {char_y_addr_reg[1]}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr_reg[1]}]
set_property BEL SLICEM.BFF [get_cells {vt/v_counter_reg[1]}]
set_property LOC SLICE_X8Y93 [get_cells {vt/v_counter_reg[1]}]
set_property BEL SLICEM.AFF [get_cells {vt/v_counter_reg[2]}]
set_property LOC SLICE_X8Y93 [get_cells {vt/v_counter_reg[2]}]
set_property BEL SLICEL.AFF [get_cells {char_x_addr_reg[1]}]
set_property LOC SLICE_X9Y90 [get_cells {char_x_addr_reg[1]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[6]}]
set_property LOC SLICE_X13Y53 [get_cells {btn_counter_reg[6]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[19]}]
set_property LOC SLICE_X13Y56 [get_cells {btn_counter_reg[19]}]
set_property BEL SLICEM.CFF [get_cells {char_y_addr_reg[0]}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr_reg[0]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[9]}]
set_property LOC SLICE_X13Y54 [get_cells {btn_counter_reg[9]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[40]}]
set_property LOC SLICE_X13Y62 [get_cells {btn_counter_reg[40]}]
set_property BEL SLICEL.AFF [get_cells {btn_counter_reg[8]}]
set_property LOC SLICE_X13Y54 [get_cells {btn_counter_reg[8]}]
set_property BEL SLICEM.AFF [get_cells {vt/h_counter_reg[2]}]
set_property LOC SLICE_X6Y91 [get_cells {vt/h_counter_reg[2]}]
set_property BEL SLICEM.AFF [get_cells {char_x_addr_reg[3]}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr_reg[3]}]
set_property BEL SLICEL.BFF [get_cells {btn_counter_reg[41]}]
set_property LOC SLICE_X13Y62 [get_cells {btn_counter_reg[41]}]
set_property BEL SLICEM.AFF [get_cells {vt/v_counter_reg[0]}]
set_property LOC SLICE_X8Y92 [get_cells {vt/v_counter_reg[0]}]
set_property BEL SLICEM.BFF [get_cells {char_x_addr_reg[4]}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr_reg[4]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[30]}]
set_property LOC SLICE_X13Y59 [get_cells {btn_counter_reg[30]}]
set_property BEL SLICEL.CFF [get_cells {btn_counter_reg[42]}]
set_property LOC SLICE_X13Y62 [get_cells {btn_counter_reg[42]}]
set_property BEL SLICEL.AFF [get_cells {vgaRed_reg[3]}]
set_property LOC SLICE_X7Y92 [get_cells {vgaRed_reg[3]}]
set_property BEL SLICEL.BFF [get_cells {vt/h_counter_reg[0]}]
set_property LOC SLICE_X7Y91 [get_cells {vt/h_counter_reg[0]}]
set_property BEL SLICEM.CFF [get_cells {char_x_addr_reg[5]}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr_reg[5]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[31]}]
set_property LOC SLICE_X13Y59 [get_cells {btn_counter_reg[31]}]
set_property BEL SLICEL.DFF [get_cells {btn_counter_reg[43]}]
set_property LOC SLICE_X13Y62 [get_cells {btn_counter_reg[43]}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[44]_i_1}]
set_property LOC SLICE_X13Y63 [get_cells {btn_counter_reg[44]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[32]_i_1}]
set_property LOC SLICE_X13Y60 [get_cells {btn_counter_reg[32]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[0]_i_1}]
set_property LOC SLICE_X13Y52 [get_cells {btn_counter_reg[0]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[36]_i_1}]
set_property LOC SLICE_X13Y61 [get_cells {btn_counter_reg[36]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[4]_i_1}]
set_property LOC SLICE_X13Y53 [get_cells {btn_counter_reg[4]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[20]_i_1}]
set_property LOC SLICE_X13Y57 [get_cells {btn_counter_reg[20]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[40]_i_1}]
set_property LOC SLICE_X13Y62 [get_cells {btn_counter_reg[40]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[28]_i_1}]
set_property LOC SLICE_X13Y59 [get_cells {btn_counter_reg[28]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[12]_i_1}]
set_property LOC SLICE_X13Y55 [get_cells {btn_counter_reg[12]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[16]_i_1}]
set_property LOC SLICE_X13Y56 [get_cells {btn_counter_reg[16]_i_1}]
set_property BEL SLICEM.CARRY4 [get_cells {accum_reg_i_4}]
set_property LOC SLICE_X12Y57 [get_cells {accum_reg_i_4}]
set_property BEL SLICEM.CARRY4 [get_cells {accum_reg_i_3}]
set_property LOC SLICE_X12Y58 [get_cells {accum_reg_i_3}]
set_property BEL SLICEM.CARRY4 [get_cells {accum_reg_i_6}]
set_property LOC SLICE_X12Y55 [get_cells {accum_reg_i_6}]
set_property BEL SLICEM.CARRY4 [get_cells {accum_reg_i_5}]
set_property LOC SLICE_X12Y56 [get_cells {accum_reg_i_5}]
set_property BEL SLICEM.CARRY4 [get_cells {accum_reg_i_2}]
set_property LOC SLICE_X12Y59 [get_cells {accum_reg_i_2}]
set_property BEL SLICEM.CARRY4 [get_cells {accum_reg_i_1}]
set_property LOC SLICE_X12Y60 [get_cells {accum_reg_i_1}]
set_property BEL SLICEM.CARRY4 [get_cells {accum_reg_i_8}]
set_property LOC SLICE_X12Y53 [get_cells {accum_reg_i_8}]
set_property BEL SLICEM.CARRY4 [get_cells {accum_reg_i_7}]
set_property LOC SLICE_X12Y54 [get_cells {accum_reg_i_7}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[24]_i_1}]
set_property LOC SLICE_X13Y58 [get_cells {btn_counter_reg[24]_i_1}]
set_property BEL SLICEL.CARRY4 [get_cells {btn_counter_reg[8]_i_1}]
set_property LOC SLICE_X13Y54 [get_cells {btn_counter_reg[8]_i_1}]
set_property BEL SLICEL.F7AMUX [get_cells {vgaRed_reg[3]_i_2}]
set_property LOC SLICE_X7Y95 [get_cells {vgaRed_reg[3]_i_2}]
set_property BEL SLICEM.B5FF [get_cells {char_x_addr_reg[6]}]
set_property LOC SLICE_X8Y90 [get_cells {char_x_addr_reg[6]}]
set_property BEL SLICEM.A5FF [get_cells {vt/v_counter_reg[9]}]
set_property LOC SLICE_X8Y92 [get_cells {vt/v_counter_reg[9]}]
set_property BEL SLICEM.A5FF [get_cells {vt/v_counter_reg[7]}]
set_property LOC SLICE_X8Y91 [get_cells {vt/v_counter_reg[7]}]
set_property BEL SLICEM.A5FF [get_cells {Hsync_reg__0}]
set_property LOC SLICE_X2Y87 [get_cells {Hsync_reg__0}]
set_property BEL SLICEL.A5FF [get_cells {vt/h_counter_reg[9]}]
set_property LOC SLICE_X7Y91 [get_cells {vt/h_counter_reg[9]}]
set_property BEL SLICEM.A5FF [get_cells {char_y_addr_reg[2]}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr_reg[2]}]
set_property BEL SLICEM.B5FF [get_cells {char_y_addr_reg[4]}]
set_property LOC SLICE_X8Y89 [get_cells {char_y_addr_reg[4]}]
set_property BEL SLICEM.A5FF [get_cells {vt/v_counter_reg[3]}]
set_property LOC SLICE_X8Y93 [get_cells {vt/v_counter_reg[3]}]
set_property BEL SLICEM.B5FF [get_cells {Vsync_reg__0}]
set_property LOC SLICE_X2Y87 [get_cells {Vsync_reg__0}]
set_property BEL SLICEM.C5FF [get_cells {vt/h_counter_reg[4]}]
set_property LOC SLICE_X6Y91 [get_cells {vt/h_counter_reg[4]}]
set_property BEL SLICEL.A5FF [get_cells {char_x_addr_reg[2]}]
set_property LOC SLICE_X9Y90 [get_cells {char_x_addr_reg[2]}]
set_property BEL SLICEL.B5FF [get_cells {vt/h_counter_reg[1]}]
set_property LOC SLICE_X7Y91 [get_cells {vt/h_counter_reg[1]}]
