set_property PACKAGE_PIN R10 [get_ports {a}]
set_property PACKAGE_PIN T10 [get_ports {b}]
set_property PACKAGE_PIN U13 [get_ports {cout}]
set_property PACKAGE_PIN T9 [get_ports {cin}]
set_property BEL IOB33.OUTBUF [get_cells {cout_OBUF_inst}]
set_property LOC U13 [get_cells {cout_OBUF_inst}]
set_property BEL IOB33.OUTBUF [get_cells {s_OBUF_inst}]
set_property LOC T13 [get_cells {s_OBUF_inst}]
set_property BEL IOB33.INBUF_EN [get_cells {b_IBUF_inst}]
set_property LOC T10 [get_cells {b_IBUF_inst}]
set_property PACKAGE_PIN T13 [get_ports {s}]
set_property BEL IOB33.INBUF_EN [get_cells {cin_IBUF_inst}]
set_property LOC T9 [get_cells {cin_IBUF_inst}]
set_property BEL IOB33.INBUF_EN [get_cells {a_IBUF_inst}]
set_property LOC R10 [get_cells {a_IBUF_inst}]
set_property BEL SLICEL.A6LUT [get_cells {s_OBUF_inst_i_1}]
set_property LOC SLICE_X0Y51 [get_cells {s_OBUF_inst_i_1}]
set_property LOCK_PINS { I0:A4 I1:A3 I2:A5 } [get_cells {s_OBUF_inst_i_1}]
set_property BEL SLICEL.A5LUT [get_cells {cout_OBUF_inst_i_1}]
set_property LOC SLICE_X0Y51 [get_cells {cout_OBUF_inst_i_1}]
set_property LOCK_PINS { I0:A4 I1:A5 I2:A3 } [get_cells {cout_OBUF_inst_i_1}]
