package require tincr 0.0

proc lastName { s } {
    return [suffix $s "/"]
}

proc suffix { s p } {
    set t [split $s $p]
    return [lindex $t [llength $t]-1]
}

proc createBlankDesignByPart { part } {
    return [tincr::designs new mydes $part]
}

proc createBlankDesign { } {
    createBlankDesignByPart xc7a100t-csg324-1
}

    # Names of library cells to process
    #         List of sites to try to place cells onto the bels of
set cellsandsites {
    { GND { }}
    { VCC { }}
    { BUFG { BUFG BUFGCTRL }}
    { RAMB36E1 { FIFO18E1 RAMB18E1 RAMBFIFO36E1 FIFO36E1 RAMB36E1 }}
    { RAMB18E1 { FIFO18E1 RAMB18E1 RAMBFIFO36E1 FIFO36E1 RAMB36E1 }}
    { FIFO18E1 { FIFO18E1 RAMB18E1 RAMBFIFO36E1 FIFO36E1 RAMB36E1 }}
    { FIFO36E1 { FIFO18E1 RAMB18E1 RAMBFIFO36E1 FIFO36E1 RAMB36E1 }}
    { MUXF7 { SLICEL SLICEM }}
    { MUXF8 { SLICEL SLICEM }}
    { LUT6 { SLICEL SLICEM }}
    { LUT5 { SLICEL SLICEM }}
    { LUT4 { SLICEL SLICEM }}
    { LUT3 { SLICEL SLICEM }}
    { LUT2 { SLICEL SLICEM }}
    { LUT1 { SLICEL SLICEM }}
    { FDRE { SLICEL SLICEM }}
    { FDSE { SLICEL SLICEM }}
    { CARRY4 { SLICEL SLICEM }}
    { RAM64X1S {SLICEL SLICEM }}
    { RAM32X1S {SLICEL SLICEM }}
}

#    { IBUF { IOB33 IOB33S IOB33M } }
#    { OBUF { IOB33 IOB33S IOB33M } }

createBlankDesign

set fo [open "cellLibrary.xml" w]

set dict [tincr::sites::unique]

puts ""

puts $fo {<?xml version="1.0" encoding="UTF-8"?>}
puts $fo "<root>"
puts $fo "  <cells>"

foreach rec $cellsandsites {
    set cname [lindex $rec 0]
    set sitenames [lindex $rec 1]
    
    incr cnt
    set libcell [get_lib_cells $cname]
    if { [llength $libcell] != 1 } then {
	puts "ERROR: cannot find libcell $cname, skipping..."
    } else {
	puts "Processing: $cname"
	puts $fo "    <cell>"
	puts $fo "      <type>[get_property NAME $libcell]</type>"
	puts $fo "      <pins>"
	set c [create_cell -reference $libcell "brent_$cnt"]
	set ps [get_pins -of $c]
	foreach p $ps {
	    puts $fo "        <pin>"
	    set pn [get_property REF_PIN_NAME $p]
#	    if { [string first "LUT" $cname] == 0 } then {
#		if { $pn == "I0" } then {
#		    set pn "A1"
#		}
#		if { $pn == "I1" } then {
#		    set pn "A2"
#		}
#		if { $pn == "I2" } then {
#		    set pn "A3"
#		}
#		if { $pn == "I3" } then {
#		    set pn "A4"
#		}
#		if { $pn == "I4" } then {
#		    set pn "A5"
#		}
#		if { $pn == "I5" } then {
#		    set pn "A6"
#		}
#	    }
	    
	    puts $fo "          <name>$pn</name>"
	    set dir [get_property DIRECTION $p]
	    if { $dir == "IN" } then {
		set dir "input"
	    } else {
		set dir "output"
	    }
	    puts $fo "          <direction>$dir</direction>"
	    puts $fo "        </pin>"
	}
	puts $fo "      </pins>"
	puts $fo "      <bels>"
	puts "Sitenames = $sitenames"

#	if { $sitenames == "ALL" } then {
	#	    set sitenames [dict keys
	# }
	foreach sn $sitenames {
	    set s [dict get $dict $sn]
	    tincr::sites::set_type $s $sn
#	    puts "SITE: $s [tincr::sites::get_type $s]"
	    foreach b [get_bels -of $s] {
#		puts "BEL: $b"
		if { [is_my_placement_legal $c $b] == 1 } then {
		    puts $fo "        <bel>"
		    puts $fo "          <id>"
		    puts $fo "            <primitive_type>[tincr::sites::get_type $s]</primitive_type>"
		    puts $fo "            <name>[lastName $b]</name>"
		    puts $fo "          </id>"
		    puts $fo "        </bel>"
		}
		unplace_cell $c
	    }
	}
	puts $fo "      </bels>"
	puts $fo "    </cell>"
	puts $fo ""
    }
}

# Down here we need to handle some cells that the Tcl-based method
# doesn't find or process correctly. 
puts $fo "    <cell>"
puts $fo "      <type>OBUF</type>"
puts $fo "      <pins>"
puts $fo "        <pin>"
puts $fo "          <name>O</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>I</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "      </pins>"
puts $fo "      <bels>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33</primitive_type>"
puts $fo "            <name>OUTBUF</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33M</primitive_type>"
puts $fo "            <name>OUTBUF</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33S</primitive_type>"
puts $fo "            <name>OUTBUF</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "      </bels>"
puts $fo "    </cell>"
puts $fo ""
puts $fo "    <cell>"
puts $fo "      <type>OBUFT</type>"
puts $fo "      <pins>"
puts $fo "        <pin>"
puts $fo "          <name>O</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>I</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>T</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "      </pins>"
puts $fo "      <bels>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33</primitive_type>"
puts $fo "            <name>OUTBUF</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33M</primitive_type>"
puts $fo "            <name>OUTBUF</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33S</primitive_type>"
puts $fo "            <name>OUTBUF</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "      </bels>"
puts $fo "    </cell>"
puts $fo ""
puts $fo "    <cell>"
puts $fo "      <type>IBUF</type>"
puts $fo "      <pins>"
puts $fo "        <pin>"
puts $fo "          <name>O</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>I</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "      </pins>"
puts $fo "      <bels>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33</primitive_type>"
puts $fo "            <name>INBUF_EN</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33M</primitive_type>"
puts $fo "            <name>INBUF_EN</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "        <bel>"
puts $fo "          <id>"
puts $fo "            <primitive_type>IOB33S</primitive_type>"
puts $fo "            <name>INBUF_EN</name>"
puts $fo "          </id>"
puts $fo "        </bel>"
puts $fo "      </bels>"
puts $fo "    </cell>"
puts $fo ""

puts $fo "    <cell>"
puts $fo "      <type>RAM32M</type>"
puts $fo "      <pins>"
puts $fo "        <pin>"
puts $fo "          <name>DIA[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DIA[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DIB[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DIB[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DIC[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DIC[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DID[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DID[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOA[1]</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOA[0]</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOB[1]</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOB[0]</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOC[1]</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOC[0]</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOD[1]</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOD[0]</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[2]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[3]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[4]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[2]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[3]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[4]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[2]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[3]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[4]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[2]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[3]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[4]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>WE</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>WCLK</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "      </pins>"
puts $fo "      <bels>"
puts $fo "      </bels>"
puts $fo "    </cell>"
puts $fo ""
puts $fo "    <cell>"
puts $fo "      <type>RAM64M</type>"
puts $fo "      <pins>"
puts $fo "        <pin>"
puts $fo "          <name>DIA</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DIB</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DIC</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DID</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOA</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOB</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOC</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>DOD</name>"
puts $fo "          <direction>output</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[2]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[3]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[4]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRA[5]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[2]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[3]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[4]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRB[5]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[2]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[3]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[4]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRC[5]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[0]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[1]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[2]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[3]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[4]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>ADDRD[5]</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>WE</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "        <pin>"
puts $fo "          <name>WCLK</name>"
puts $fo "          <direction>input</direction>"
puts $fo "        </pin>"
puts $fo "      </pins>"
puts $fo "      <bels>"
puts $fo "      </bels>"
puts $fo "    </cell>"
puts $fo ""
puts $fo "  </cells>"
puts $fo "</root>"
close $fo
