
####################################################################################
# Generated by Vivado 2016.2 built on 'Thu Jun  2 16:32:40 MDT 2016' by 'xbuild'
# Command Used: write_xdc -force C:/Users/ecestudent/Desktop/RSCP/series7/bramdsp.tcp/constraints.rsc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
